apiserver:
  replicaCount: 1
  image:
    repository: bitnami/kafka
    pullPolicy: Always
    tag: 3.2-debian-11
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
  resources: {}
  hosts: []
  ingress: []
  ports:
    - name: db1
      port: 9092
      type: ClusterIP
      protocol: tcp
      targetPort: 9092
    - name: db2
      port: 9093
      type: ClusterIP
      protocol: tcp
      targetPort: 9093
  envs: 
    # For secure, please DO NOT allow it in production
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"

    # Notice: These passwords should be changed to a random string
    - name: KAFKA_CERTIFICATE_PASSWORD
      value: kafka
    - name: KAFKA_CLIENT_PASSWORDS
      value: kafka

    - name: KAFKA_HEAP_OPTS
      value: -Xmx1024m -Xms1024m
    - name: KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL
      value: PLAIN
    - name: KAFKA_TLS_CLIENT_AUTH
      value: none

    # For KRAFT
    - name: KAFKA_ENABLE_KRAFT
      value: "yes"
    # To gen it: please use command: 
    # uuidgen | tr -d '-' | base64 | cut -b 1-22
    - name: KAFKA_KRAFT_CLUSTER_ID
      value: ""
    - name: KAFKA_CFG_PROCESS_ROLES
      value: broker,controller
    - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
      value: CONTROLLER
    - name: KAFKA_CFG_LISTENERS
      value: PLAINTEXT://:9092,CONTROLLER://:9093
    - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
      value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: PLAINTEXT://127.0.0.1:9092
    - name: KAFKA_CFG_BROKER_ID
      value: "1"
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_NODE_ID
      value: "1"
    - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
      value: 1@127.0.0.1:9093
    - name: KAFKA_CFG_PROCESS_ROLES
      value: broker,controller
  mounts: 
    - name: data
      type: hostPath
      path: /bitnami/kafka
      pathSrc: /data/db/kafka1

imagePullSecrets: []

autoscaling:
  enabled: false
